author: TomyLobo
database: false
description: Allows creating horse/boat/dragon routes
main: eu.tomylobo.routes.Routes
name: routes
startup: postworld
url: https://github.com/TomyLobo/routes
version: '1.0'

commands:
  routes:
    aliases: [ro]
